export const CyberPrompts = [
    'Create a visual illustration of how firewalls work to protect a system.',
    'Design a network security architecture diagram highlighting layers of protection.',
    'Illustrate cyber attack scenarios and the defense steps taken.',
    'Generate an infographic explaining the concept of data encryption.',
    'Visualize the process of threat detection and response.',
    'Craft a network map highlighting vulnerable points and ways to secure them.',
    'Create an illustration depicting the roles of security technologies such as antivirus and antispyware.',
    'Design concepts of security at the application, system, and network levels.',
    'Illustrate identity and access-based security model.',
    'Create a flowchart to demonstrate the system security testing process.',
    'Design a security schema for secure software development, including Linux.',
    'Create an infographic on phishing attacks and prevention methods.',
    'Visualize the principles of security in operating systems, including Linux.',
    'Generate a map illustrating common cybersecurity threats.',
    'Illustrate the security concepts of cloud computing.',
    'Design steps for security observation and log analysis.',
    'Create a heatmap of common cybersecurity threats.',
    'Illustrate the concept of sandboxing to isolate threats.',
    'Design the process of system security auditing.',
    'Create a security diagram for Internet of Things (IoT).',
    'Illustrate security concepts in open-source software development.',
  ];
  
  
